Revert ":sparkles: move to typescript action"
This reverts commit 49a995f15879f71bba99c887b1ef2ce9cac47407.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,13 +1,10 @@
 # Github action to create a preview for pullrequests
-# Brand Boosting GmbH
+# Brand Boosting GmbH | David Süßlin
 name: 'Create Shopify Theme Preview'
 description: 'Create a Shopify Theme Preview'
-author: 'Brand Boosting GmbH'
-
 branding:
   icon: shopping-cart
   color: green
-
 inputs:
   shopify_flag_store:
     description: 'Store URL, like your-store.myshopify.com'
@@ -24,15 +21,104 @@ inputs:
     default: '.'
     required: false
   timezone:
-    description: 'TZ identifier'
+    description: "TZ identifier"
     required: false
-    default: 'UTC'
+    default: "UTC"
+runs:                   
+  using: "composite"
+  steps:
+    - name: Set timezone
+      uses: szenius/set-timezone@v1.2
+      with:
+        timezoneLinux: ${{ inputs.timezone }}
+    - name: Get Date  # Get current date
+      id: date
+      shell: bash
+      run: echo "date=$(date +'%d-%m-%Y ')" >> $GITHUB_OUTPUT
+    - name: Get Time  # Get current time
+      id: time
+      run: echo "time=$(date +'%H:%M:%S')" >> $GITHUB_OUTPUT
+      shell: bash
+    - name: Comment Loading # Create skeleton table and visualize loading state
+      uses: peter-evans/create-or-update-comment@v3.1.0
+      with:
+        comment-id: ${{ github.event.comment.id }}
+        body: |
+          | Name | Status | Preview | Editor | Date | Time |
+          | :--- | :----- | :------ | :------ | :------ | :----- |
+          | ${{ inputs.shopify_flag_store }} | 🔄 Loading |  |  | ${{ steps.date.outputs.date }} | ${{ steps.time.outputs.time }}
+        
+          *created by Brand Boosting GmbH | PotatoBot* [View on GitHub Marketplace](https://github.com/marketplace/actions/create-shopify-theme-preview)
+        edit-mode: replace
+    - uses: actions/checkout@v4 # Action checkout@v4
+    - name: Checkout Pull Request # Set the right branch for the commented PR
+      run: gh pr checkout ${{ github.event.issue.number }}
+      env:
+        GITHUB_TOKEN: ${{ github.token }}
+      shell: bash
+    - uses: actions/setup-node@v4  # Action setup-node@v4
+      with:
+        node-version: 18
+    - uses: ruby/setup-ruby@v1 # Action setup-ruby@v1
+      with:
+        ruby-version: 3.1
+        bundler: 'latest'
+    - name: Install Shopify CLI 
+      run: npm install -g @shopify/cli@latest @shopify/theme@latest
+      shell: bash
+    - name: Check Version
+      run: shopify version
+      shell: bash
+    - name: Build step 
+      run: ${{ inputs.build_step }}
+      shell: bash
+    - name: Create Preview Link # and safe the returned value in an output object
+      id: link
+      shell: bash
+      env:
+        # Store URL, like your-store.myshopify.com
+        SHOPIFY_FLAG_STORE: ${{ inputs.shopify_flag_store }}
+        # Password generated from Theme Access app
+        SHOPIFY_CLI_THEME_TOKEN: ${{ inputs.shopify_cli_theme_token }}
+      run: |
+        echo 'JSON_RESPONSE<<EOF' >> $GITHUB_OUTPUT
+        shopify theme push --unpublished --json --development --path ${{ inputs.dir}} >> $GITHUB_OUTPUT || true
+        echo 'EOF' >> $GITHUB_OUTPUT
+    - name: Format Data # Safe output in a temporary txt file and extract the last line with requested links
+      run: |
+        echo '${{ steps.link.outputs.JSON_RESPONSE }}' > 'temp.txt'
+        echo 'LINK<<DEL' >> $GITHUB_OUTPUT
+        tail -n1 temp.txt >> $GITHUB_OUTPUT
+        echo 'DEL' >> $GITHUB_OUTPUT
+      id: temp
+      shell: bash
+    - name: Comment Link  # Override the loading comment from the start with the actual values and links
+      uses: peter-evans/create-or-update-comment@v3.1.0
+      with:
+        comment-id: ${{ github.event.comment.id }}
+        body: |
+          | Name | Status | Preview | Editor | Date | Time |
+          | :--- | :----- | :------ | :------ | :------ | :----- |
+          | ${{ inputs.shopify_flag_store }} | ✅ Ready | <a href="${{ fromJSON(steps.temp.outputs.LINK).theme.preview_url }}" target="_blank">Preview</a> | [Editor](${{ fromJSON(steps.temp.outputs.LINK).theme.editor_url }}) | ${{ steps.date.outputs.date }} | ${{ steps.time.outputs.time }}
+        
+          *created by Brand Boosting GmbH | PotatoBot* [View on GitHub Marketplace](https://github.com/marketplace/actions/create-shopify-theme-preview)
+        reactions: hooray
+        edit-mode: replace
+    - name: Output Step Failed # Create skeleton table and visualize failed state
+      if: ${{ failure() }}
+      uses: peter-evans/create-or-update-comment@v3.1.0
+      with:
+        comment-id: ${{ github.event.comment.id }}
+        body: |
+          | Name | Status | Preview | Editor | Date | Time |
+          | :--- | :----- | :------ | :------ | :------ | :----- |
+          | ${{ inputs.shopify_flag_store }} | ❌ Failed |  |  | ${{ steps.date.outputs.date }} | ${{ steps.time.outputs.time }}
+          
+          ❌ 'Create Preview Link' failed ❌
 
-# Define your outputs here.
-outputs:
-  time:
-    description: 'Your output description here'
+          Please check if the following `inputs` are set correctly:
+          - `shopify_cli_theme_token` [(?)](https://shopify.dev/themes/tools/theme-access)
+          - `shopify_flag_store` 
 
-runs:
-  using: node20
-  main: dist/index.js
+          *created by Brand Boosting GmbH | PotatoBot* <p style="float: right;">[View on GitHub Marketplace](https://github.com/marketplace/actions/create-shopify-theme-preview)</p>
+        edit-mode: replace
